name: Build Sygnal ARMv7

on:
  push:
    branches: 
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------
      # Clone Element-web source
      # -----------------------------
      - name: Clone Sygnal source
        run: |
          git clone https://github.com/element-hq/sygnal.git sygnal
          cd sygnal
          git checkout main
        
      - name: Set lowercase owner
        id: vars
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Patch Dockerfile variables
        run: |
        
          cd sygnal/docker
        
          # 1. Inject a custom ARG at the top of the Dockerfile
          # sed -i '1i ARG MY_PLATFORM_OVERRIDE' Dockerfile
          
          # 2. Replace $BUILDPLATFORM with the new variable
          # This target specifically the 'uv' stage 
          # sed -i 's/--platform=\$BUILDPLATFORM/--platform=\$MY_PLATFORM_OVERRIDE/g' Dockerfile

          # This command finds the 'uv' FROM line and inserts the platform flag.
          # sed -i 's|FROM ghcr.io/astral-sh/uv|FROM --platform=\$MY_PLATFORM_OVERRIDE ghcr.io/astral-sh/uv|' Dockerfile
          
          # Optional: Verify the change in the logs
          grep "FROM" Dockerfile

      - name: Build and push ARMv7 image
        uses: docker/build-push-action@v6
        with:
          context: sygnal
          file: sygnal/docker/Dockerfile
          platforms: linux/armv7 # linux/arm/v7
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.owner_lc }}/sygnal:armv7
          build-args: |
            MY_PLATFORM_OVERRIDE=linux/armv7
