name: Build Sygnal ARMv7

on:
  push:
    branches: 
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------
      # Clone Element-web source
      # -----------------------------
      - name: Clone Sygnal source
        run: |
          git clone https://github.com/element-hq/sygnal.git sygnal
          cd sygnal
          git checkout main
        
      - name: Set lowercase owner
        id: vars
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Patch Dockerfile variables
        run: |
        
          cd sygnal/docker
        
          # This command finds the 'uv' FROM line and inserts the platform flag.
          sed -i 's|FROM ghcr.io/astral-sh/uv|FROM --platform=\$BUILDPLATFORM ghcr.io/astral-sh/uv|' Dockerfile

          # Inject environment variables for uv to target ARMv7
          # We insert these right after the FROM line in the builder stage
          sed -i '/AS builder/a ENV UV_VISUAL_ARCH=armv7\\nENV UV_SYSTEM_PYTHON=1' Dockerfile

          # 3. Ensure the final runtime uses the correct Python base for ARMv7
          # This forces the final stage to use the platform you defined in the workflow
          sed -i 's|FROM python:|FROM --platform=linux/arm/v7 python:|g' Dockerfile
          
          # Optional: Verify the change in the logs
          grep "FROM" Dockerfile

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.vars.outputs.owner_lc }}/sygnal
          tags: |
          
            # 1. Main 'armv7' tag
            type=raw,value=armv7
            # 2. 'latest' tag (only on main branch)
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # 3. Version tag (e.g. v0.14.0-armv7) if you use git tags
            type=semver,pattern={{version}},suffix=-armv7
          flavor: |
            latest=false

      - name: Build and push ARMv7 image
        uses: docker/build-push-action@v6
        with:
          context: sygnal
          file: sygnal/docker/Dockerfile
          platforms: linux/arm/v7 # linux/arm/v7
          push: true
          # Use the tags generated by the metadata step
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # tags: ghcr.io/${{ steps.vars.outputs.owner_lc }}/sygnal:armv7

